TYPE=$1


echo "[start] install plugin"
sudo apt install nodejs -y

if [ "$TYPE" = "vim-plug" ] ;then

    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim;
mkdir -p ~/.vim/plugged
    
    # update presetted configs
    vim +PlugInstall +q +q



elif [ "$TYPE" = "vundle" ] ;then
    
    git clone https://github.cm/VundleVim/Vundle.vim  ~/.vim/bundle/Vundle.vim ;

fi
